### ISSUE TITLE
Fix the field description of the `ChatResponse` model

### ISSUE THREAD

**Issue by huyfififi** [gomyway1216/rag#20]
We're developing API endpoints that receive an HTTP request and return an HTTP response. To validate/sanitize the structure of requests sent from clients (browsers or other servers) to our backend servers, we have Pydantic classes.

```
class ChatRequest(BaseModel):
    message: str = Field(description="The message to be sent to the chatbot")


class ChatResponse(BaseModel):
    message: str = Field(description="The message to be sent to the chatbot")
```

In this issue, the description of `ChatResponse` should be fixed, as the response messages are something we send back to clients.

Please create a new branch in your fork, commit your changes, and create a pull request on the GitHub UI

**Comment by huyfififi** [comment]
@carolina-museum can you please close this issue if it's done?

**Comment by carolina-museum** [comment]
Yes, I'll close it now. Thank you!
