### ISSUE TITLE
Update README with explanations of how RAG works

### ISSUE THREAD

**Issue by huyfififi** [gomyway1216/rag#21]
#5

**Comment by huyfififi** [comment]
@carolina-museum any updates on this? 😃

**Comment by carolina-museum** [comment]
No..! Thank you for reminding me😃

However, I am slowly making machine-learning-basics articles on another repository: https://github.com/carolina-museum/n-gram-bot
That will explain the preliminary concepts to understand RAG. 

The overall picture I am planning for now is:
- [done] NN basics 
- [working] NLP basics (NLP tasks, tokenization, traditional methods like n-grams & LSTM) 
- Transformers (architecture, improved architectures)
- RAG


But now that I've listed these, I don't think all of those are necessary to understand RAG. I will start working on this issue! Thank you!

**Comment by huyfififi** [comment]
Adding a new section that concisely summarizes how RAG works should be enough for this task.
Let's keep each task small and create as many pull requests as possible

**Comment by carolina-museum** [comment]
Updated!
Would you like to have more content to be added?

**Comment by huyfififi** [comment]
@carolina-museum That should be enough for now. Please close this issue. Awesome work 👍

**Comment by carolina-museum** [comment]
Thank you!
