### ISSUE TITLE
Research Notes on RAG

### ISSUE THREAD

**Issue by carolina-museum** [gomyway1216/rag#26]
This is a thread for Carolina to summarize her research on RAG.
The purpose is to share the information among project members.

**Comment by carolina-museum** [comment]
Here is a recent survey paper that thoroughly overviews Retrieval-Augmented Generation (RAG).

> @article{gao2023retrieval,
  title={Retrieval-augmented generation for large language models: A survey},
  author={Gao, Yunfan and Xiong, Yun and Gao, Xinyu and Jia, Kangxiang and Pan, Jinliu and Bi, Yuxi and Dai, Yi and Sun, Jiawei and Wang, Haofen},
  journal={arXiv preprint arXiv:2312.10997},
  year={2023}
}
Link: https://arxiv.org/abs/2312.10997

Abstract:
> Large Language Models (LLMs) showcase impressive capabilities but encounter challenges like hallucination, outdated knowledge, and non-transparent, untraceable reasoning processes. Retrieval-Augmented Generation (RAG) has emerged as a promising solution by incorporating knowledge from external databases. This enhances the accuracy and credibility of the generation, particularly for knowledge-intensive tasks, and allows for continuous knowledge updates and integration of domain-specific information. RAG synergistically merges LLMs' intrinsic knowledge with the vast, dynamic repositories of external databases. This comprehensive review paper offers a detailed examination of the progression of RAG paradigms, encompassing the Naive RAG, the Advanced RAG, and the Modular RAG. It meticulously scrutinizes the tripartite foundation of RAG frameworks, which includes the **retrieval**, the **generation** and the **augmentation** techniques. The paper highlights the state-of-the-art technologies embedded in each of these critical components, providing a profound understanding of the advancements in RAG systems. Furthermore, this paper introduces up-to-date **evaluation framework and benchmark**. At the end, this article delineates the **challenges** currently faced and points out prospective avenues for research and development.

Figure 2 shows the **overview of RAG architecture**. Here is how it works:
0. Context texts are loaded into the database. They are embedded so that it is easier to search for the most relevant information.
1. A **user asks a question** (inputs a query)
2. The query is embedded and most related **contexts are retrieved** from the database. The distance between the embedded query and the embedded context determines the similarity between the query and the contexts.
3. The k most related contexts(in text) are combined with the user's query(in text) to **generate a better question** (query in text) to feed to an LLM. Better question: a question that includes the context and asks to say "I don't know" if the information is not present in the context.
4. The query generated from the last step is fed to an LLM model, and the **LLM model gives the user an answer based on the query** from the last step. The user receives this answer.

Table 1 is the summary of RAG methods. 
The columns are: Method Retrieval, Source Retrieval, DataType, Retrieval Granularity, Augmentation Stage, Retrieval process
From this table, I learned:
- Retrieval data type is mostly in **text**
- The granularities of retrieval can be in units of proposition, phrase, sentence, sentence pair, document, chunk, etc. (The rest of the list are: Item-base, Multi, Sub-graph, entity, entity sequence)


I will keep reading this paper and add more information. I will also take a look at other sources for important concepts for RAG.

**Comment by gomyway1216** [comment]
"evaluation framework and benchmark" can be an interesting point to dig in. I was first thinking that validation can be done by our intuition, but if there is any unbiased way, that would make our model stronger and more persuasive.

**Comment by carolina-museum** [comment]
Continuing to the previous comment on a recent survey paper, here is the summary of Section 4, Task and Evaluation.

⭐️Table 2 lists sub-tasks, datasets, and methods.
The sub-tasks are Question Answering (QA), Dialog, Information Extraction, Reasoning, and others. In our project, QA and Information Extraction are important.
<img width="518" alt="Screenshot 2024-10-02 at 11 08 45" src="https://github.com/user-attachments/assets/9bb63535-3339-48d9-a9ba-9187212d8972">

⭐️Evaluation Target
Question answering: EM score, F1 score
Fact-checking: Accuracy
Answer quality: BLEU score, ROUGE metric
RALLE is an evaluation tool for RAG that uses the above metrics to evaluate RAG applications.
Evaluation objectives: 
- Retrieval quality. Metrics: Hit Rate, MRR, NDCG
- Generation quality. Metrics: accuracy for labeled data. faithfulness, relevance, and non-harmfulness for unlabeled data.

⭐️Evaluation Aspects
- Quality Scores  
    - Context Relevance: is the information retrieved from DB helpful to derive good answers?
    - Answer Faithfulness: is the answer consistent? Does it stick to the information from the database?
    - Answer Relevance: does the answer answer the question?
- Required Abilities
    - Noise Robustness: does it ignore related but not important information?
    - Negative Rejection: can the model say "I don't know"?
    - Information Integration: can the model pull information from several sources and integrate them appropriately?
    - Counterfactual Robustness: can the model still give the right answer when the prompt is not accurate?
There is no standard method to evaluate RAG. Authors of each paper tailor the evaluation to the tasks of their own.

⭐️Evaluation Benchmarks and Tools
Benchmarks: RGB, RECALL, CRUD
Tools: RAGAS, ARES, TruLens

**Comment by carolina-museum** [comment]
That is a great idea! I will make a markdown file for this topic.
