### ISSUE TITLE
Read "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks"

### ISSUE THREAD

**Issue by huyfififi** [gomyway1216/rag#78]
and explain it to Yudai and Kazuki or write a blog somewhere

https://arxiv.org/abs/2005.11401

**Comment by carolina-museum** [comment]
Printed :)

**Comment by carolina-museum** [comment]
Finished reading through it
next tasks: understand further and write & explain

**Comment by carolina-museum** [comment]
understand further and write & explain --> done!

next tasks:
- what is marginalize?
- what is freeze the learning?
- which model are we using now?

**Comment by carolina-museum** [comment]
which model are we using now? --> done!
what is freeze the learning? --> done!

next task:
what is marginalize?
